[package]
name = "http_proxy_client"
version = "20241016.0.0"
authors = ["Alex.F <gfreezy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { workspace = true }
config = { path = "../config" }
base64 = { workspace = true }
async-tls = { workspace = true }
parking_lot = { workspace = true }
